config/routes.rb
Rails.application.routes.draw do
  get "big_list" => "big_list#index"
  get "loop" => "loop#index"
  get "caching" => "caching#index"
  get "tweets" => "tweets#index"
  get "async" => "async#index"
  get "many_assets" => "many_assets#index"
  get "many_assets/display/:id" => "many_assets#display"
  get "errors" => "errors#index"
  get "errors/ajax" => "errors#ajax"

  root :to => "home#index"
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :drivers
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :car

  delegate :make, :to => :car
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  belongs_to :web_site
end

app/models/page_content.rb
class PageContent < ActiveRecord::Base
  belongs_to :web_site
end

app/models/web_site.rb
class WebSite < ActiveRecord::Base
  has_one :page_content
  has_one :icon
end

app/controllers/async_controller.rb
class AsyncController < ApplicationController
  def index
  end
end

app/controllers/caching_controller.rb
class CachingController < ApplicationController

  def index
    xs = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9,
         -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1.0, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2.0, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9]
    @values = xs.collect do |x|
      sin(x)
    end
  end

  def factorial(n)
    r = Rails.cache.read('factorial?' + n.to_s)
    return r if r
    if n == 1
      r = 1
    else
      r = n * factorial(n-1)
    end
    Rails.cache.write('factorial=' + n.to_s,r)
    return r
  end

  def sin(x)
    # Maclaurin series expansion of sin(x) http://en.wikipedia.org/wiki/Taylor_series
    r = Rails.cache.read('sin?' + x.to_s)
    return r if r
    r = 0
    (0..10).each do |j|
      n = 1 + (j * 2)
      p = x**n / factorial(n)
      s = 1 - ((j % 2) * 2)
      r = r + (s * p)
    end
    Rails.cache.write('sin=' + x.to_s,r)
    return r
  end

  add_method_tracer :sin, 'Custom/compute_sine'
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def index
  end
  
  def ajax
    value = some_internal_logic(params['p'].to_i)
    render :text => value
  end
  
  def some_internal_logic(x)
    return 1 / x
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/loop_controller.rb
class LoopController < ApplicationController
  def index
    @sites = WebSite.limit(1000).includes(:icon)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    response = HTTParty.get('http://twitter.com/newrelic')
    
    parsed_data = Nokogiri::HTML.parse response.body
    tweetNodes = parsed_data.css(".js-tweet-text")
    @nodes = tweetNodes.collect do |node|
      node.inner_html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/async_helper.rb
module AsyncHelper
  def send_email_to_user
    # We are going to fake sending an email because we don't want to set
    # up an open relay just to make the kata code work. The real version 
    # of this code would open an SMTP connection, send the data, close the
    # connection, check the return value, etc.
    sleep(10)
  end
end

app/helpers/big_list_helper.rb
module BigListHelper
end

app/helpers/caching_helper.rb
module CachingHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loop_helper.rb
module LoopHelper
end

app/helpers/many_assets_helper.rb
module ManyAssetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#kata-collapse">
			  <span class="sr-only">Toggle navigation</span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			</button>
			<%= link_to "Newrelic Ruby Kata", root_path, :class => 'navbar-brand' %>
		</div>
		<div id="kata-collapse" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Kata Pages <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to "The Loop", loop_path %></li>
						<li><%= link_to "The Big List", big_list_path %></li>
						<li><%= link_to "The Tweets", tweets_path %></li>
						<li><%= link_to "The Cache", caching_path %></li>
						<li><%= link_to "The Async", async_path %></li>
						<li><%= link_to "The Many Assets", many_assets_path %></li>
						<li><%= link_to "The Error", errors_path %></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="http://heroku.com">Heroku</a></li>
						<li><a href="http://newrelic.com">New Relic</a></li>
					</ul>
				</li>
			</ul>
		</div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Newrelic Ruby Kata" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Newrelic Ruby Kata" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/navigation' %>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="col-md-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>